console.time('load-items');
const itemsByCategory = {};
const items = (function() {
  function item(name, recipes, status) {
    for (const recipe of recipes) {
      if (recipe.materials) {
        recipe._materials = {};
        for (const material in recipe.materials) {
          const v = recipe.materials[material];
          const k = material.split('|').map(function(f) {
            return '<u>' + f + '</u>'
          }).join(' or ');
          delete recipe.materials[material];
          recipe.materials[k] = v;
          recipe._materials[k.toLowerCase()] = v;
        }
        if (recipe.furnitures) {
          recipe._furnitures = [];
          recipe.furnituresHTML = recipe.furnitures.map(function(f) {
            recipe._furnitures.push(f.toLowerCase());
            return '<u>' + f + '</u>'
          });
        }
      } else if (recipe.other) {
        recipe._other = recipe.other.toLowerCase().replace(/<\/?u>/g, '');
      } else if (recipe.buy) {
        recipe._buy = recipe.buy.replace(/<\/?u>/g, '');
      }
    }
    if (status && status.category) {
      status.categoryHTML = status.category.map(function(c) {
        return '<u>' + c + '</u>'
      });
    }
    const _item = {name, _name: name.toLowerCase(), urlName: name.replace(/\s/g, '_').replace(/\'/, '%27'), recipes, status};
    /*if (status && status.category) {
      for (const category in status.category) {
        if (itemsByCategory[category]) {
          itemsByCategory[category].push(_item);
        }
      }
    }*/
    return _item;
  }
  // STATUSES
  const STATUS_PICKAXE = {category: ['tool', 'pickaxe']},
        STATUS_DRILL = {category: ['tool', 'drill']},
        STATUS_AXE = {category: ['tool', 'axe']},
        STATUS_HAMAXE = {category: ['tool', 'hamaxe']},
        STATUS_CHAINSAW = {category: ['tool', 'chainsaw']},
        STATUS_HAMMER = {category: ['tool', 'hammer']},
        STATUS_HOOK = {category: ['tool', 'hook']},
        STATUS_FISHING_POLE = {category: ['tool', 'fishing pole']},
        STATUS_MOVEMENT = {category: ['tool', 'movement']},
        STATUS_ENV = {category: ['tool', 'environment']},
        STATUS_BLOCK_WAND = {category: ['tool', 'block wand']},
        STATUS_WIRING = {category: ['tool', 'wiring']},
        STATUS_PAINT = {category: ['tool', 'painting']},
        STATUS_OTHER_TOOL = {category: ['tool', 'other tool']},
        STATUS_PARTY = {category: ['tool', 'party']},
        STATUS_SHORTSWORD = {category: ['meelee weapon', 'shortsword']},
        STATUS_LONGSWORD = {category: ['meelee weapon', 'longsword']},
        STATUS_MAGIC_SWORD = {category: ['meelee weapon', 'magic sword']},
        STATUS_SPEAR = {category: ['meelee weapon', 'spear']},
        STATUS_FLAIL = {category: ['meelee weapon', 'flail']},
        STATUS_LAUNCHED = {category: ['meelee weapon', 'flail']},
        STATUS_BOOMERANG = {category: ['meelee weapon', 'boomerang']},
        STATUS_YOYO = {category: ['meelee weapon', 'yoyo']},
        STATUS_OTHER_MEELEE = {category: ['meelee weapon', 'other meelee']},
        STATUS_BOW = {category: ['ranged weapon', 'bow']},
        STATUS_REPEATER = {category: ['ranged weapon', 'repeater']},
        STATUS_ARROW = {category: ['ammo', 'arrow']},
        STATUS_GUN = {category: ['ranged weapon', 'gun']},
        STATUS_BULLET = {category: ['ammo', 'bullet']},
        STATUS_LAUNCHER = {category: ['ranged weapon', 'launcher']},
        STATUS_ROCKET = {category: ['ammo', 'rocket']},
        STATUS_OTHER_RANGED = {category: ['ranged weapon', 'other ranged']},
        STATUS_DART = {category: ['ammo', 'dart']},
        STATUS_OTHER_AMMO = {category: ['ammo', 'other ammo']},
        STATUS_WAND = {category: ['magic weapon', 'wand']},
        STATUS_MAGIC_GUN = {category: ['magic weapon', 'magic gun']},
        STATUS_SPELL_TOME = {category: ['magic weapon', 'spell tome']},
        STATUS_OTHER_MAGIC = {category: ['magic weapon', 'other magic']},
        STATUS_SUMMON = {category: ['summon weapon']},
        STATUS_SENTRY_SUMMON = {category: ['summon weapon', 'sentry summon']},
        STATUS_THROWING = {category: ['consumable weapon', 'throwing']},
        STATUS_EXPLOSIVE = {category: ['consumable weapon', 'explosive']},
        STATUS_PLACEABLE_WEAPON = {category: ['placeable weapon']}
        ;
  return [
  // PICKAXE
    item('Copper Pickaxe', [{materials: {'Copper Bar': 12, 'Wood': 4}}, {buy: 'from the <u>Merchant</u>', price: {silver: 5}}], STATUS_PICKAXE),
    item('Cactus Pickaxe', [{materials: {'Cactus': 15}}], STATUS_PICKAXE),
    item('Tin Pickaxe', [{materials: {'Tin Bar': 12, 'Wood': 4}}], STATUS_PICKAXE),
    item('Iron Pickaxe', [{materials: {'Iron Bar': 12, 'Wood': 3}}], STATUS_PICKAXE),
    item('Lead Pickaxe', [{materials: {'Lead Bar': 12, 'Wood': 4}}], STATUS_PICKAXE),
    item('Silver Pickaxe', [{materials: {'Silver Bar': 12, 'Wood': 4}}], STATUS_PICKAXE),
    item('Tungsten Pickaxe', [{materials: {'Tungsten Bar': 12, 'Wood': 4}}], STATUS_PICKAXE),
    item('Bone Pickaxe', [{other: '<u>Drop</u> by Undead Miner(2%)'}], STATUS_PICKAXE),
    item('Gold Pickaxe', [{materials: {'Gold Bar': 12, 'Wood': 4}}], STATUS_PICKAXE),
    item('Candy Cane Pickaxe', [{other: 'Get from <u>Presents</u>(0.63%) dropped durning the <u>Chrismas event</u>(7.69%)'}], STATUS_PICKAXE),
    item('Platinum Pickaxe', [{materials: {'Platinum Bar': 12, 'Wood': 4}}], STATUS_PICKAXE),
    item('Nightmare Pickaxe', [{materials: {'Demonite Bar': 12, 'Shadow Scale': 6}}], STATUS_PICKAXE),
    item('Deathbringer Pickaxe', [{materials: {'Crimtane Bar': 12, 'Tissue Sample': 6}}], STATUS_PICKAXE),
    item('Molten Pickaxe', [{materials: {'Hellstone Bar': 20}}], STATUS_PICKAXE),
    item('Reaver Shark', [{other: '<u>Fishing</u> in the <u>Ocean</u>'}], STATUS_PICKAXE),
    item('Cobalt Pickaxe', [{materials: {'Cobalt Bar': 18}}], STATUS_PICKAXE),
    item('Palladium Pickaxe', [{materials: {'Palladium Bar': 15}}], STATUS_PICKAXE),
    item('Mythril Pickaxe', [{materials: {'Mythril Bar': 15}}], STATUS_PICKAXE),
    item('Orichalcum Pickaxe', [{materials: {'Orichalcum Bar': 18}}], STATUS_PICKAXE),
    item('Adamantite Pickaxe', [{materials: {'Adamantite Bar': 18}}], STATUS_PICKAXE),
    item('Titanium Pickaxe', [{materials: {'Titanium Bar': 20}}], STATUS_PICKAXE),
    item('Chlorophyte Pickaxe', [{materials: {'Chlorophyte Bar': 18}}], STATUS_PICKAXE),
    item('Spectre Pickaxe', [{materials: {'Spectre Bar': 18}}], STATUS_PICKAXE),
    item('Pickaxe Axe', [{materials: {'Hallowed Bar': 18, 'Soul of Fright': 1, 'Soul of Might': 1, 'Soul of Sight': 1}}], {category: ['tool', 'drax']}),
    item('Shroomite Digging Claw', [{materials: {'Shroomite Bar': 18}}], {category: ['tool', 'drax']}),
  // DRILL
    item('Cobalt Drill', [{materials: {'Cobalt Bar': 15}}], STATUS_DRILL),
    item('Palladium Drill', [{materials: {'Palladium Bar': 18}}], STATUS_DRILL),
    item('Mythril Drill', [{materials: {'Mythril Bar': 15}}], STATUS_DRILL),
    item('Orichalcum Drill', [{materials: {'Orichalcum Bar': 18}}], STATUS_DRILL),
    item('Adamantite Drill', [{materials: {'Adamantite Bar': 18}}], STATUS_DRILL),
    item('Titanium Drill', [{materials: {'Titanium Bar': 18}}], STATUS_DRILL),
    item('Drax', [{materials: {'Hallowed Bar': 18, 'Soul of Fright': 1, 'Soul of Might': 1, 'Soul of Sight': 1}}], STATUS_DRILL),
    item('Chlorophyte Drill', [{materials: {'Chlorophyte Bar': 18}}], STATUS_DRILL),
    item('Laser Drill', [{other: '<u>Drop</u> by <u>Martian Saucer</u>'}], STATUS_DRILL),
  // AXE
    item('Copper Axe', [{materials: {'Copper Bar': 9, 'Wood': 3}}, {buy: '<u>Merchant</u>', price: {silver: 4}}], STATUS_AXE),
    item('Tin Axe', [{materials: {'Tin Bar': 9, 'Wood': 3}}], STATUS_AXE),
    item('Iron Axe', [{materials: {'Iron Bar': 9, 'Wood': 3}}], STATUS_AXE),
    item('Lead Axe', [{materials: {'Lead Bar': 9, 'Wood': 3}}], STATUS_AXE),
    item('Silver Axe', [{materials: {'Silver Bar': 9, 'Wood': 3}}], STATUS_AXE),
    item('Tungsten Axe', [{materials: {'Tungsten Bar': 9, 'Wood': 3}}], STATUS_AXE),
    item('Gold Axe', [{materials: {'Gold Bar': 9, 'Wood': 3}}], STATUS_AXE),
    item('Platinum Axe', [{materials: {'Platinum Bar': 9, 'Wood': 3}}], STATUS_AXE),
    item('War Axe of the Night', [{materials: {'Demonite Bar': 10}}], STATUS_AXE),
    item('Blood Lust Cluster', [{materials: {'Crimtane Bar': 10}}], STATUS_AXE),
    item('Cobalt Waraxe', [{materials: {'Cobalt Bar': 10}}], STATUS_AXE),
    item('Palladium Waraxe', [{materials: {'Palladium Bar': 10}}], STATUS_AXE),
    item('Mythril Waraxe', [{materials: {'Mythril Bar': 10}}], STATUS_AXE),
    item('Orichalcum Waraxe', [{materials: {'Orichalcum Bar': 10}}], STATUS_AXE),
    item('Adamantite Waraxe', [{materials: {'Adamantite Bar': 12}}], STATUS_AXE),
    item('Titanium Waraxe', [{materials: {'Titanium Bar': 12}}], STATUS_AXE),
    item('Chlorophyte Waraxe', [{materials: {'Chlorophyte Bar': 18}}], STATUS_AXE),
  // HAMAXE
    item('Meteor Hamaxe', [{materials: {'Meteorite Bar': 35}}], STATUS_HAMAXE),
    item('Molten Hamaxe', [{materials: {'Hellstone Bar': 15}}], STATUS_HAMAXE),
    item('Spectre Hamaxe', [{materials: {'Spectre Bar': 18}}], STATUS_HAMAXE),
    item('The Axe', [{other: '<u>Drop</u> by <u>Plantera</u>(0.5%)'}], STATUS_HAMAXE),
    item('Solar Flare Hamaxe', [{materials: {'Luminite Bar': 12, 'Solar Fragment': 14}}], STATUS_HAMAXE),
    item('Vortex Hamaxe', [{materials: {'Luminite Bar': 12, 'Vortex Fragment': 14}}], STATUS_HAMAXE),
    item('Nebula Hamaxe', [{materials: {'Luminite Bar': 12, 'Nebula Fragment': 14}}], STATUS_HAMAXE),
    item('Stardust Hamaxe', [{materials: {'Luminite Bar': 12, 'Stardust Fragment': 14}}], STATUS_HAMAXE),
  // Drax
    item('Picksaw', [{other: '<u>Drop</u> by <u>Golem</u>(12.5%)'}], {category: ['tool', 'drax']}),
  // Chainsaw
    item('Sawtooth Shark', [{other: '<u>Fishing</u> in the <u>Ocean</u>'}], STATUS_CHAINSAW),
    item('Cobalt Chainsaw', [{materials: {'Cobalt Bar': 10}}], STATUS_CHAINSAW),
    item('Palladium Chainsaw', [{materials: {'Palladium Bar': 10}}], STATUS_CHAINSAW),
    item('Mythril Chainsaw', [{materials: {'Mythril Bar': 10}}], STATUS_CHAINSAW),
    item('Orichalcum Chainsaw', [{materials: {'Orichalcum Bar': 10}}], STATUS_CHAINSAW),
    item('Adamantite Chainsaw', [{materials: {'Adamantite Bar': 12}}], STATUS_CHAINSAW),
    item('Titanium Chainsaw', [{materials: {'Titanium Bar': 12}}], STATUS_CHAINSAW),
    item('Chlorophyte Chainsaw', [{materials: {'Chlorophyte Bar': 18}}], STATUS_CHAINSAW),
    item('Butcher\'s Chainsaw', [{other: '<u>Drop</u> by <u>Butcher</u>(2.5%)'}], STATUS_CHAINSAW),
  // Hammer
    item('Wooden Hammer', [{materials: {'Wood': 8}}], STATUS_HAMMER),
    item('Copper Hammer', [{materials: {'Copper Bar': 10, 'Wood': 3}}], STATUS_HAMMER),
    item('Boreal Wood Hammer', [{materials: {'Boreal Wood': 8}}], STATUS_HAMMER),
    item('Palm Wood Hammer', [{materials: {'Palm Wood': 8}}], STATUS_HAMMER),
    item('Rich Mahogany Hammer', [{materials: {'Rich Mahogany': 8}}], STATUS_HAMMER),
    item('Tin Hammer', [{materials: {'Tin Bar': 10, 'Wood': 3}}], STATUS_HAMMER),
    item('Iron Hammer', [{materials: {'Iron Bar': 10, 'Wood': 3}}], STATUS_HAMMER),
    item('Ebonwood Hammer', [{materials: {'Ebonwood': 8}}], STATUS_HAMMER),
    item('Shadewood Hammer', [{materials: {'Shadewood': 8}}], STATUS_HAMMER),
    item('Lead Hammer', [{materials: {'Lead Bar': 10, 'Wood': 3}}], STATUS_HAMMER),
    item('Pearlwood Hammer', [{materials: {'Pealwood': 8}}], STATUS_HAMMER),
    item('Silver Hammer', [{materials: {'Silver Bar': 10, 'Wood': 3}}], STATUS_HAMMER),
    item('Tungsten Hammer', [{materials: {'Tungsten Bar': 10, 'Wood': 3}}], STATUS_HAMMER),
    item('Gold Hammer', [{materials: {'Gold Bar': 10, 'Wood': 3}}], STATUS_HAMMER),
    item('Platinum Hammer', [{materials: {'Platinum Bar': 10, 'Wood': 3}}], STATUS_HAMMER),
    item('The Breaker', [{materials: {'Demonite Bar': 10, 'Shadow Scale': 5}}], STATUS_HAMMER),
    item('Flesh Hammer', [{materials: {'Crimtane Bar': 10, 'Tissue Sample': 5}}], STATUS_HAMMER),
    item('Rockfish', [{other: '<u>Fishing</u> in the <u>Underground</u>, <u>Cavern</u>, <u>The Underworld</u>'}], STATUS_HAMMER),
    item('Pwnhammer', [{other: '<u>Drop</u> by <u>Wall of Flesh</u>(100%)'}], STATUS_HAMMER),
    item('Hammush', [{buy: '<u>Truffle</u>', price: {gold: 40}}], STATUS_HAMMER),
    item('Chlorophyte Warhammer', [{materials: {'Chlorophyte Bar': 18}}], STATUS_HAMMER),
    item('Chlorophyte Jackhammer', [{materials: {'Chlorophyte Bar': 10}}], STATUS_HAMMER),
  // Hooks
    item('Grappling Hook', [{materials: {'Chain': 3, 'Hook': 1}}, {buy: '<u>Goblin Tinkerer</u>', price: {gold: 2}}], STATUS_HOOK),
    item('Amethyst Hook', [{materials: {'Amethyst': 15}}], STATUS_HOOK),
    item('Topaz Hook', [{materials: {'Topaz': 15}}], STATUS_HOOK),
    item('Sapphire Hook', [{materials: {'Sapphire': 15}}], STATUS_HOOK),
    item('Emerald Hook', [{materials: {'Emerald': 15}}], STATUS_HOOK),
    item('Ruby Hook', [{materials: {'Ruby': 15}}], STATUS_HOOK),
    item('Diamond Hook', [{materials: {'Diamond': 15}}], STATUS_HOOK),
    item('Web Slinger', [{other: 'Get from the <u>Web Covered Chest</u>'}], STATUS_HOOK),
    item('Skeletron Hand', [{other: '<u>Drop</u> by <u>Skeletron</u>(14.28%)'}], STATUS_HOOK),
    item('Slime Hoo', [{other: '<u>Drop</u> by <u>King Slime</u>(50%)'}], STATUS_HOOK),
    item('Fish Hook', [{other: 'Quest reward of the <u>Angler</u>(1/60)'}], STATUS_HOOK),
    item('Ivy Whip', [{materials: {'Vine': 3, 'Jungle Spores': 12}}], STATUS_HOOK),
    item('Bat Hook', [{other: 'Get from the <u>Goodie Bag</u>(0.66%) dropped durning the <u>Halloween event</u>(1.25%)'}], STATUS_HOOK),
    item('Candy Cane Hook', [{other: 'Get from the <u>Present</u>(0.63%) dropped durning the <u>Chrismas event</u>(7.69%)'}], STATUS_HOOK),
    item('Dual Hook', [{other: '<u>Drop</u> by <u>Mimic</u>(14.29%)'}], STATUS_HOOK),
    item('Thorn Hook', [{other: '<u>Drop</u> by <u>Plantera</u>(10%)'}], STATUS_HOOK),
    item('Illuminant Hook', [{other: '<u>Drop</u> by <u>Hallowed Mimic</u>(25%)'}], STATUS_HOOK),
    item('Worm Hook', [{other: '<u>Drop</u> by <u>Corrupt Mimic</u>(20%)'}], STATUS_HOOK),
    item('Tendon Hook', [{other: '<u>Drop</u> by <u>Crimson Mimic</u>(20%)'}], STATUS_HOOK),
    item('Anti-Gravity Hook', [{other: '<u>Drop</u> by <u>Martian Saucer</u>(11.11%)'}], STATUS_HOOK),
    item('Chrismas Hook', [{other: '<u>Drop</u> by <u>Everscream</u>(5.19~7.78%)'}], STATUS_HOOK),
    item('Lunar Hook', [{materials: {'Nebula Fragment': 6, 'Solar Fragment': 6, 'Stardust Fragment': 6, 'Vortex Fragment': 6}}], STATUS_HOOK),
  // Fishing Pole
    item('Wood Fishing Pole', [{materials: {'Wood': 8}}], STATUS_FISHING_POLE),
    item('Reinforced Fishing Pole', [{materials: {'Iron Bar|Lead Bar': 8}}], STATUS_FISHING_POLE),
    item('Fisher of Souls', [{materials: {'Demonite Bar': 8}}], STATUS_FISHING_POLE),
    item('Fleshcatcher', [{materials: {'Crimtane Bar': 8}}], STATUS_FISHING_POLE),
    item('Fiberglass Fishing Pole', [{other: 'Get from the <u>Ivy Chest</u>(2%)'}], STATUS_FISHING_POLE),
    item('Mechanic\'s Rod', [{buy: '<u>Mechanic</u> durning Waning Cresent Moon and Hardmode', price: {gold: 20}}], STATUS_FISHING_POLE),
    item('Sitting Duck\'s Fishing Pole', [{buy: '<u>Traveling Merchant</u>', price: {gold: 35}}], STATUS_FISHING_POLE),
    item('Hotline Fishing Hook', [{other: 'Quest reward of the <u>Angler</u>(1/100) after 25th quests in Hardmode'}], STATUS_FISHING_POLE),
    item('Golden Fishing Rod', [{other: 'Quest reward of the <u>Angler</u>(1/250) after 75th quests'}], STATUS_FISHING_POLE),
  // Movement
    item('Magic Mirror', [{other: 'Get from the <u>Gold Chest</u>'}], STATUS_MOVEMENT),
    item('Ice Mirror', [{other: 'Get from the <u>Ice Chest</u>'}], STATUS_MOVEMENT),
    item('Cell Phone', [{materials: {'PDA': 1, 'Magic Mirror': 1}}, {materials: {'PDA': 1, 'Ice Mirror': 1}}], STATUS_MOVEMENT),
    item('Rod of Discord', [{other: '<u>Drop</u> by <u>Chaos Elemental</u>(0.2%)'}], STATUS_MOVEMENT),
    item('Portal Gun', [{other: '<u>Drop</u> by <u>Moon Lord</u>(100%) if not in the inventory'}], STATUS_MOVEMENT),
    item('Rope Coil', [{materials: {'Rope': 10}}], STATUS_MOVEMENT),
    item('Umbrella', [{other: 'Get from the <u>Chest</u> in <u>Surface</u>'}], STATUS_MOVEMENT),
  // Environment
    item('Vile Powder', [{materials: {'Vile Mushroom': 1}}, {buy: '<u>Dryad</u> at the <u>Blood Moon</u>', price: {silver: 1}}], STATUS_ENV),
    item('Vicious Powder', [{materials: {'Vicious Mushroom': 1}}, {buy: '<u>Dryad</u> at the <u>Blood Moon</u>', price: {silver: 1}}], STATUS_ENV),
    item('Purification Powder', [{buy: '<u>Dryad</u> not at the <u>Blood Moon</u>', price: {copper: 75}}], STATUS_ENV),
    item('Unholy Water', [{materials: {'Bottled Water': 10, 'Corrupt Seeds': 1, 'Ebonsand Block': 1}}], STATUS_ENV),
    item('Blood Water', [{materials: {'Bottled Water': 10, 'Crimson Seeds': 1, 'Crimsand Block': 1}}], STATUS_ENV),
    item('Holy Water', [{materials: {'Bottled Water': 10, 'Hallowed Seeds': 1, 'Pixie Dust': 2}}], STATUS_ENV),
    item('Staff of Regrowth', [{other: 'Get from the <u>Ivy Chest</u>'}], STATUS_ENV),
    item('Clentaminator', [{buy: '<u>Steampunker</u>', price: {platinum: 2}}], STATUS_ENV),
  // Place Block
    item('Ice Rod', [{buy: '<u>Wizard</u>', price: {gold: 50}}], STATUS_BLOCK_WAND),
    item('Dirt Rod', [{buy: '<u>Dryad</u>', price: {gold: 5}}], STATUS_BLOCK_WAND),
    item('Leaf Wand', [{other: 'Get from the <u>Living Wood Chest</u>'}], STATUS_BLOCK_WAND),
    item('Living Wood Wand', [{other: 'Get from the <u>Living Wood Chest</u>'}], STATUS_BLOCK_WAND),
    item('Rich Mahogany Leaf Wand', [{other: 'Get from the <u>Ivy Chest</u>'}], STATUS_BLOCK_WAND),
    item('Living Mahogany Wand', [{other: 'Get from the <u>Ivy Chest</u>'}], STATUS_BLOCK_WAND),
    item('Hive Wand', [{other: '<u>Drop</u> by <u>Queen Bee</u>(33.3%)'}], STATUS_BLOCK_WAND),
    item('Bone Wand', [{other: '<u>Drop</u> by <u>Angry Bones</u>(0.4%)'}], STATUS_BLOCK_WAND),
  // Wire
    item('Red Wrench', [{buy: '<u>Mechanic</u>', price: {gold: 2}}], STATUS_WIRING),
    item('Blue Wrench', [{buy: '<u>Mechanic</u>', price: {gold: 2}}], STATUS_WIRING),
    item('Green Wrench', [{buy: '<u>Mechanic</u>', price: {gold: 2}}], STATUS_WIRING),
    item('Yellow Wrench', [{buy: '<u>Mechanic</u>', price: {gold: 2}}], STATUS_WIRING),
    item('Wire Cutter', [{buy: '<u>Mechanic</u>', price: {gold: 2}}], STATUS_WIRING),
    item('Multicolor Wrench', [{materials: {'Red Wrench': 1, 'Blue Wrench': 1, 'Green Wrench': 1, 'Yellow Wrench': 1, 'Wire Cutter': 1}}], STATUS_WIRING),
    item('The Grand Design', [{materials: {'Multicolor Wrench': 1, 'Mechanical Lens': 1, 'Ruler': 1, 'Wire': 60}}], STATUS_WIRING),
  // Painting
    item('Paintbrush', [{buy: '<u>Painter</u>', price: {gold: 1}}], STATUS_PAINT),
    item('Paint Roller', [{buy: '<u>Painter</u>', price: {gold: 1}}], STATUS_PAINT),
    item('Paint Scraper', [{buy: '<u>Painter</u>', price: {gold: 1}}], STATUS_PAINT),
    item('Spectre Paintbrush', [{materials: {'Spectre Bar': 8}}], STATUS_PAINT),
    item('Spectre Paint Roller', [{materials: {'Spectre Bar': 8}}], STATUS_PAINT),
    item('Spectre Paint Scraper', [{materials: {'Spectre Bar': 8}}], STATUS_PAINT),
  // Other Tools
    item('Bucket', [{materials: {'Iron Bar|Lead Bar': 3}}], STATUS_OTHER_TOOL),
    item('Bottomless Water Bucket', [{other: 'Quest reward of the <u>Angler</u>(1/70) after 10th quests in Hardmode'}], STATUS_OTHER_TOOL),
    item('Super Absorbant Sponge', [{other: 'Quest reward of the <u>Angler</u>(1/70) after 10th quests in Hardmode'}], STATUS_OTHER_TOOL),
    item('Magic Dropper', [{materials: {'Empty Dropper': 1}, furnitures: ['Crystal Ball', 'Liquids']}], STATUS_OTHER_TOOL),
    item('Sickle', [{buy: '<u>Merchant</u>', price: {silver: 60}}], STATUS_OTHER_TOOL),
    item('Bug Net', [{buy: '<u>Merchant</u>', price: {silver: 25}}], STATUS_OTHER_TOOL),
    item('Golden Bug Net', [{other: 'Quest reward of the <u>Angler</u>(1/70)'}], STATUS_OTHER_TOOL),
    item('Breathing Reed', [{other: 'Get from the <u>Water Chest</u>'}], STATUS_OTHER_TOOL),
    item('Binoculars', [{other: '<u>Drop</u> by <u>Eye of Cthulhu</u>(2.5%)'}], STATUS_OTHER_TOOL),
    item('Money Trough', [{other: '<u>Drop</u> by <u>Drippler</u>(0.5%)'}, {other: '<u>Drop</u> by <u>Blood Zombie</u>(0.5%)'}], STATUS_OTHER_TOOL),
  // Party Item
    item('Bubble Wand', [{buy: '<u>Party Girl</u>', price: {gold: 5}}], STATUS_PARTY),
    item('Unicorn on a Stick', [{other: '<u>Drop</u> by <u>Unicorn</u>(1.0%)'}], STATUS_PARTY),
    item('Whoopie Cushion', [{other: '<u>Drop</u> by <u>Giant Worm</u>(1.0%)'}, {other: '<u>Drop</u> by <u>Digger</u>(1.0%)'}], STATUS_PARTY),
    item('Beach Ball', [{buy: '<u>Party Girl</u>', price: {copper: 20}}], STATUS_PARTY),
    item('Water Gun', [{buy: '<u>Traveling Merchant</u>', price: {gold: 1, silver: 50}}], STATUS_PARTY),
    item('Slime Gun', [{other: '<u>Drop</u> by <u>King Slime</u>(50%)'}], STATUS_PARTY),
  
  // Short Sword
    item('Copper Shortsword', [{materials: {'Copper Bar': 7}}], STATUS_SHORTSWORD),
    item('Tin Shortsword', [{materials: {'Tin Bar': 7}}], STATUS_SHORTSWORD),
    item('Iron Shortsword', [{materials: {'Iron Bar': 7}}], STATUS_SHORTSWORD),
    item('Lead Shortsword', [{materials: {'Lead Bar': 7}}], STATUS_SHORTSWORD),
    item('Silver Shortsword', [{materials: {' Bar': 6}}], STATUS_SHORTSWORD),
    item('Tungsten Shortsword', [{materials: {'Tungsten Bar': 6}}], STATUS_SHORTSWORD),
    item('Gold Shortsword', [{materials: {'Gold Bar': 7}}], STATUS_SHORTSWORD),
    item('Platinum Shortsword', [{materials: {'Platinum Bar': 7}}], STATUS_SHORTSWORD),
  // Long Sword
    item('Wooden Sword', [{materials: {'Wood': 7}}], STATUS_LONGSWORD),
    item('Copper Broadsword', [{materials: {'Copper Bar': 8}}], STATUS_LONGSWORD),
    item('Boreal Wood Sword', [{materials: {'Boreal Wood': 7}}], STATUS_LONGSWORD),
    item('Palm Wood Sword', [{materials: {'Palm Bar': 7}}], STATUS_LONGSWORD),
    item('Rich Mahogany Sword', [{materials: {'Rich Mahogany': 7}}], STATUS_LONGSWORD),
    item('Tin Broadsword', [{materials: {'Tin Bar': 8}}], STATUS_LONGSWORD),
    item('Cactus Sword', [{materials: {'Cactus': 10}}], STATUS_LONGSWORD),
    item('Iron Broadsword', [{materials: {'Iron Bar': 8}}], STATUS_LONGSWORD),
    item('Ebonwood Sword', [{materials: {'Ebonwood': 7}}], STATUS_LONGSWORD),
    item('Shadewood Sword', [{materials: {'Shadewood': 7}}], STATUS_LONGSWORD),
    item('Lead Broadsword', [{materials: {'Lead Bar': 8}}], STATUS_LONGSWORD),
    item('Pealwood Sword', [{materials: {'Pealwood': 7}}], STATUS_LONGSWORD),
    item('Silver Broadsword', [{materials: {'Silver Bar': 8}}], STATUS_LONGSWORD),
    item('Tungsten Broadsword', [{materials: {'Tungsten Bar': 8}}], STATUS_LONGSWORD),
    item('Zombie Arm', [{other: '<u>Drop</u> by <u>Zombie</u>(0.4%)'}], STATUS_LONGSWORD),
    item('Bladed Glove', [{other: '<u>Drop</u> by <u>Weak Enemies</u>(0.05%) dropped durning the <u>Halloween Event</u>'}], STATUS_LONGSWORD),
    item('Gold Broadsword', [{materials: {'Gold Bar': 8}}], STATUS_LONGSWORD),
    item('Stylish Scissors', [{other: '<u>Drop</u> by <u>Stylist</u>(12.5%)'}], STATUS_LONGSWORD),
    item('Mandible Blade', [{other: '<u>Drop</u> by <u>Antlion Charger</u>(2%) in the Underground Desert'}], STATUS_LONGSWORD),
    item('Platinum Broadsword', [{materials: {'Platinum Bar': 8}}], STATUS_LONGSWORD),
    item('Candy Cane Sword', [{other: 'Get from <u>Presents</u>(0.64%) dropped durning the <u>Chrismas event</u>(7.69%)'}], STATUS_LONGSWORD),
    item('Classy Cane', [{other: '<u>Drop</u> by <u>Tax Collector</u>(12.5%)'}], STATUS_LONGSWORD),
    item('Bone Sword', [{other: '<u>Drop</u> by <u>Skeleton</u>(0.5%)'}], STATUS_LONGSWORD),
    item('Katana', [{buy: '<u>Traveling Merchant</u>', price: {gold: 4}}], STATUS_LONGSWORD),
    item('Light\'s Bane', [{materials: {'Demonite Bar': 10}}], STATUS_LONGSWORD),
    item('Muramasa', [{other: 'Get from the <u>Gold Chest</u> in <u>Dungeon</u>'}], STATUS_LONGSWORD),
    item('Arkhalis', [{other: 'Get from the <u>Enchanted Sword Shrine</u>'}], STATUS_LONGSWORD),
    item('Exotic Scimitar', [{other: '<u>Drop</u> by <u>Dye Trader</u>(12.5%)'}], STATUS_LONGSWORD),
    item('Phaseblade', [{materials: {'Meteorite Bar': 15, 'Any Gem': 10}}], STATUS_LONGSWORD),
    item('Blood Butcherer', [{materials: {'Crimtane Bar': 10}}], STATUS_LONGSWORD),
    item('Purple Clubberfish', [{other: '<u>Fishing</u> in <u>The Corruption</u>'}], STATUS_LONGSWORD),
    item('Blade of Grass', [{materials: {'Jungle Spores': 12, 'Stinger': 15}}], STATUS_LONGSWORD),
    item('Falcon Blade', [{other: 'Get from the <u>Iron Crate</u>'}], STATUS_LONGSWORD),
    item('Slap Hand', [{buy: '<u>Skeleton Merchant</u> at the <u>Blood Moon</u>', price: {gold: 25}}], STATUS_LONGSWORD),
    item('Fiery Greatsword', [{materials: {'Hellstone Bar': 20}}], STATUS_LONGSWORD),
    item('Breaker Blade', [{other: '<u>Drop</u> by <u>Wall of Flesh</u>(16.67%)'}], STATUS_LONGSWORD),
    item('Cobalt Sword', [{materials: {'Cobalt Bar': 10}}], STATUS_LONGSWORD),
    item('Palladium Sword', [{materials: {'Palladium Bar': 12}}], STATUS_LONGSWORD),
    item('Phasesaber', [{materials: {'Crystal Shard': 8, 'Phaseblade': 1}}], STATUS_LONGSWORD),
    item('Night\'s Edge', [{materials: {'Blood Butcherer': 1, 'Blade of Grass': 1, 'Fiery Greatsword': 1, 'Muramasa': 1}, furnitures: ['Demon Altar']}], STATUS_LONGSWORD),
    item('Mythril Sword', [{materials: {'Mythril Bar': 10}}], STATUS_LONGSWORD),
    item('Orichalcum Sword', [{materials: {'Orichalcum Bar': 12}}], STATUS_LONGSWORD),
    item('Cutlass', [{other: '<u>Drop</u> by <u>Pirate Enemies(excluding the Parrot)</u>(0.5%) durning the <u>Pirate Invasion</u>'}], STATUS_LONGSWORD),
    item('Adamantite Sword', [{materials: {'Adamantite Bar': 12}}], STATUS_LONGSWORD),
    item('Titanium Sword', [{materials: {'Titanium Bar': 13}}], STATUS_LONGSWORD),
    item('Excalibur', [{materials: {'Hallowed Bar': 12}}], STATUS_LONGSWORD),
    item('Keybrand', [{other: '<u>Drop</u> by <u>Any Armored Bones</u>(16.67%)'}], STATUS_LONGSWORD),
    item('Fetid Baghnakhs', [{other: '<u>Drop</u> by <u>Crimson Mimic</u>(20%)'}], STATUS_LONGSWORD),
    item('Psycho Knife', [{other: '<u>Drop</u> by <u>Psycho</u>(2.5%)'}], STATUS_LONGSWORD),
  // Magic Sword
    item('Ice Blade', [{other: 'Get from the <u>Ice Chest</u>'}], STATUS_MAGIC_SWORD),
    item('Starfury', [{other: 'Get from the <u>Skyware Chest</u>'}], STATUS_MAGIC_SWORD),
    item('Enchanted Sword', [{other: 'Get from the <u>Enchanted Sword Shrine</u>'}], STATUS_MAGIC_SWORD),
    item('Bee Keeper', [{other: '<u>Drop</u> by <u>Queen Bee</u>(33%)'}], STATUS_MAGIC_SWORD),
    item('Ice Sickle', [{other: '<u>Drop</u> by <u>Armored Viking</u>, <u>Ice Elemental</u>, <u>Icy Merman</u>, <u>Ice Tortoise</u>(0.56%)'}], STATUS_MAGIC_SWORD),
    item('Chlorophyte Saber', [{materials: {'Chlorophyte Bar': 12}}], STATUS_MAGIC_SWORD),
    item('Seedler', [{other: '<u>Drop</u> by <u>Plantera</u>(14.29%)'}], STATUS_MAGIC_SWORD),
    item('Beam Sword', [{other: '<u>Drop</u> by <u>Armored Skeleton</u>(0.67%)'}], STATUS_MAGIC_SWORD),
    item('Bladetongue', [{other: '<u>Fishing</u> in <u>The Crimson</u> in Hardmode'}], STATUS_MAGIC_SWORD),
    item('Death Sickle', [{other: '<u>Drop</u> by <u>Reaper</u>(2.5%)'}], STATUS_MAGIC_SWORD),
    item('True Excalibur', [{materials: {'Excalibur': 1, 'Broken Hero Sword': 1}}], STATUS_MAGIC_SWORD),
    item('Chlorophyte Claymore', [{materials: {'Chlorophyte Bar': 12}}], STATUS_MAGIC_SWORD),
    item('The Horseman\'s Blade', [{other: '<u>Drop</u> by <u>Pumpking</u>(1.79~14.29%)'}], STATUS_MAGIC_SWORD),
    item('Chrismas Tree Sword', [{other: '<u>Drop</u> by <u>Everscream</u>(5.19~7.78%)'}], STATUS_MAGIC_SWORD),
    item('True Night\'s Edge', [{materials: {'Night\'s Edge': 1, 'Broken Hero Sword': 1}}], STATUS_MAGIC_SWORD),
    item('Terra Blade', [{materials: {'True Excalibur': 1, 'True Night\'s Edge': 1}}], STATUS_MAGIC_SWORD),
    item('Influx Waver', [{other: '<u>Drop</u> by <u>Martian Saucer</u>(11.1%)'}], STATUS_MAGIC_SWORD),
    item('Star Wrath', [{other: '<u>Drop</u> by <u>Moon Lord</u>(11.1%)'}], STATUS_MAGIC_SWORD),
    item('Meowmere', [{other: '<u>Drop</u> by <u>Moon Lord</u>(11.1%)'}], STATUS_MAGIC_SWORD),
    // Spear
    item('Spear', [{other: 'Get from the <u>Chest</u> in Surface'}], STATUS_SPEAR),
    item('Trident', [{other: 'Get from the <u>Water Chest</u>'}], STATUS_SPEAR),
    item('The Rotted Fork', [{other: 'Get from the <u>Crimson Heart</u>(20%) or <u>Crimson Crate</u>(3.33%)'}], STATUS_SPEAR),
    item('Swordfish', [{other: '<u>Fishing</u> in the <u>Ocean</u>'}], STATUS_SPEAR),
    item('Dark Lance', [{other: 'Get from the <u>Shadow Chest</u>'}], STATUS_SPEAR),
    item('Cobalt Naginata', [{materials: {'Cobalt Bar': 10}}], STATUS_SPEAR),
    item('Palladium Pike', [{materials: {'Palladium Bar': 12}}], STATUS_SPEAR),
    item('Mythril Halberd', [{materials: {'Mythril Bar': 10}}], STATUS_SPEAR),
    item('Orichalcum Halberd', [{materials: {'Orichalcum Bar': 12}}], STATUS_SPEAR),
    item('Adamantite Glaive', [{materials: {'Adamantite Bar': 12}}], STATUS_SPEAR),
    item('Titanium Trident', [{materials: {'Titanium Bar': 13}}], STATUS_SPEAR),
    item('Gungnir', [{materials: {'Hallowed Bar': 12}}], STATUS_SPEAR),
    item('Chlorophyte Partisan', [{materials: {'Chlorophyte Bar': 12}}], STATUS_SPEAR),
    item('Mushroom Spear', [{buy: '<u>Truffle</u>', price: {gold: 70}}], STATUS_SPEAR),
    item('Obsidian Swordfish', [{other: '<u>Fishing</u> with the <u>Hotline Fishing Hook</u>'}], STATUS_SPEAR),
    item('North Pole', [{other: '<u>Drop</u> by <u>Ice Queen</u>(4.4~7.52%)'}], STATUS_SPEAR),
  // Flail
    item('Ball O\' Hurt', [{other: 'Get from the <u>Shadow Orb</u>(20%) or <u>Corrupt Crate</u>(3.33%)'}], STATUS_FLAIL),
    item('The Meatball', [{materials: {'Crimtane Bar': 10, 'Tissue Sample': 5}}], STATUS_FLAIL),
    item('Blue Moon', [{other: 'Get from the <u>Gold Chest</u>(20%) in Dungeon or <u>Dungeon Crate</u>(2.08%)'}], STATUS_FLAIL),
    item('Sunfury', [{other: 'Get from the <u>Shadow Chest</u>'}], STATUS_FLAIL),
    item('Dao of Pow', [{materials: {'Dark Shard': 1, 'Light Shard': 1, 'Soul of Light': 7, 'Soul of Night': 7}}], STATUS_FLAIL),
    item('Flower Pow', [{other: '<u>Drop</u> by <u>Plantera</u>(14.29%)'}], STATUS_FLAIL),
  // Launched
    item('Chain Knife', [{other: '<u>Drop</u> by <u>Cave Bat</u>(0.4%)'}], STATUS_LAUNCHED),
    item('Anchor', [{other: 'Get from the <u>Wooden Crate</u>(4%)'}], STATUS_LAUNCHED),
    item('KO Cannon', [{other: '<u>Drop</u> by <u>Any Surface Enemies</u> durning a <u>Blood Moon</u> in Hardmode(0.1%)'}], STATUS_LAUNCHED),
    item('Chain Guillotines', [{other: '<u>Drop</u> by <u>Corrupt Mimic</u>(20%)'}], STATUS_LAUNCHED),
    item('Flairon', [{other: '<u>Drop</u> by <u>Duke Fishron</u>(20%)'}], STATUS_LAUNCHED),
    item('Golem Fist', [{other: '<u>Drop</u> by <u>Golem</u>(12.5%)'}], STATUS_LAUNCHED),
    item('Solar Eruption', [{materials: {'Solar Fragment': 18}}], STATUS_LAUNCHED),
  // Boomerang
    item('Wooden Boomerang', [{other: 'Get from the <u>Chest</u> in <u>Surface</u>'}], STATUS_BOOMERANG),
    item('Enchanted Boomerang', [{other: 'Get from the <u>Gold Chest</u> in <u>Underground</u>'}], STATUS_BOOMERANG),
    item('Ice Boomerang', [{other: 'Get from the <u>Ice Chest</u>'}], STATUS_BOOMERANG),
    item('Fruitcake Chakram', [{other: 'Get from <u>Presents</u>(0.63%) dropped durning the <u>Chrismas event</u>(7.69%)'}], STATUS_BOOMERANG),
    item('Blood Machete', [{other: '<u>Drop</u> by <u>Weak Enemies</u>(0.05%) dropped durning the <u>Halloween Event</u>'}], STATUS_BOOMERANG),
    item('Thorn Chakram', [{materials: {'Jungle Spores': 6, 'Stinger': 9}}], STATUS_BOOMERANG),
    item('Flamarang', [{materials: {'Enchanted Boomerang': 1, 'Hellstone Bar': 15}}], STATUS_BOOMERANG),
    item('Drax', [{materials: {'Hallowed Bar': 4, 'Soul of Light': 3, 'Soul of Might': 5}}], STATUS_BOOMERANG),
    item('Bananarang', [{other: '<u>Drop</u> by <u>Clown</u>(3.33%)'}], STATUS_BOOMERANG),
    item('Possessed Hachet', [{other: '<u>Drop</u> by <u>Golem</u>(12.5%)'}], STATUS_BOOMERANG),
    item('Paladin\'s Hammer', [{other: '<u>Drop</u> by <u>Paladin</u>(2.86%)'}], STATUS_BOOMERANG),
  // Yoyo
    item('Wooden Yoyo', [{materials: {'Wood': 12, 'Cobweb': 20}}], STATUS_YOYO),
    item('Rally', [{other: '<u>Drop</u> by <u>Crawdad</u>, <u>Giant Shelly</u>, <u>Salamander</u>(20%)'}], STATUS_YOYO),
    item('Malaise', [{materials: {'Demonite Bar': 12}}], STATUS_YOYO),
    item('Artery', [{materials: {'Crimtane Bar': 12}}], STATUS_YOYO),
    item('Amazon', [{materials: {'Rich Mahogany': 8, 'Stinger': 2, 'Vine': 1, 'Jungle Spores': 3}}], STATUS_YOYO),
    item('Code 1', [{buy: '<u>Traveling Merchant</u> only after the Eye of Cthulhu has been defeated', price: {gold: 5}}], STATUS_YOYO),
    item('Valor', [{other: 'Get from the <u>Gold Chest</u> in <u>Dungeon</u>'}], STATUS_YOYO),
    item('Cascade', [{other: '<u>Drop</u> by <u>The Underworld Enemies</u>(0.25%) only after the Skeletron has been defeated'}], STATUS_YOYO),
    item('Format:C', [{buy: '<u>Skeleton Merchant</u> in Hardmode and moon phases 1 (full), 2, 3, and 4 only.', price: {gold: 20}}], STATUS_YOYO),
    item('Gradient', [{buy: '<u>Skeleton Merchant</u> in Hardmode and moon phases 5 (new), 6, 7, and 8 only.', price: {gold: 20}}], STATUS_YOYO),
    item('Chik', [{materials: {'Wooden Yoyo': 1, 'Crystal Shard': 15, 'Sould of Light': 10}}], STATUS_YOYO),
    item('Hel-Fire', [{other: '<u>Drop</u> by <u>Cavern and The Underworld Enemies</u>(0.5%) in Hardmode'}], STATUS_YOYO),
    item('Amarok', [{other: '<u>Drop</u> by <u>Snow Enemies</u>(1.25%) in Hardmode'}], STATUS_YOYO),
    item('Code 2', [{buy: '<u>Traveling Merchant</u> only after Any Mechanical Boss has been defeated', price: {gold: 25}}], STATUS_YOYO),
    item('Yelets', [{other: '<u>Drop</u> by <u>Jungle Enemies</u>(0.5%) in Hardmode'}], STATUS_YOYO),
    item('Red\'s Throw', [{other: 'Get from the <u>Treasure Bag</u>'}], STATUS_YOYO),
    item('Valkyrie Yoyo', [{other: 'Get from the <u>Treasure Bag</u>'}], STATUS_YOYO),
    item('Kraken', [{other: '<u>Drop</u> by <u>Dungeon Enemies</u>(0.5%) only after the Plantera has been defeated'}], STATUS_YOYO),
    item('The Eye of Cthulhu', [{other: '<u>Drop</u> by <u>Mothron</u>(25%) only after the Plantera has been defeated'}], STATUS_YOYO),
    item('Terrarian', [{other: '<u>Drop</u> by <u>Moon Lord</u>(11.11%)'}], STATUS_YOYO),
  // Other Weapon
    item('Vampire Knives', [{other: 'Get from the <u>Crimson Chest</u> in <u>Dungeon</u>'}], STATUS_OTHER_MEELEE),
    item('Scourge of the Corruptor', [{other: 'Get from the <u>Corruption Chest</u> in <u>Dungeon</u>'}], STATUS_OTHER_MEELEE),
    item('Flying Knife', [{other: '<u>Drop</u> by <u>Hallowed Mimic</u>(25%)'}], STATUS_OTHER_MEELEE),
    item('Shadowflame Knife', [{other: '<u>Drop</u> by <u>Goblin Summoner</u>(16.7%)'}], STATUS_OTHER_MEELEE),
    item('Daybreak', [{materials: {'Solar Fragment': 18}}], STATUS_OTHER_MEELEE),
  // Bow
    item('Wooden Bow', [{materials: {'Wood': 10}}], STATUS_BOW),
    item('Boreal Wood Bow', [{materials: {'Boreal Wood': 10}}], STATUS_BOW),
    item('Copper Bow', [{materials: {'Copper Bar': 7}}], STATUS_BOW),
    item('Palm Wood Bow', [{materials: {'Palm WOod': 10}}], STATUS_BOW),
    item('Rich Mahogany Bow', [{materials: {'Rich Mahogany': 10}}], STATUS_BOW),
    item('Tin Bow', [{materials: {'Tin Bar': 7}}], STATUS_BOW),
    item('Iron Bow', [{materials: {'Iron Bar': 7}}], STATUS_BOW),
    item('Ebonwood Bow', [{materials: {'Ebonwood': 10}}], STATUS_BOW),
    item('Shadewood Bow', [{materials: {'Shadewood': 10}}], STATUS_BOW),
    item('Lead Bow', [{materials: {'Lead Bar': 7}}], STATUS_BOW),
    item('Pealwood Bow', [{materials: {'Pealwood': 10}}], STATUS_BOW),
    item('Silver Bow', [{materials: {'Silver Bar': 7}}], STATUS_BOW),
    item('Tungsten Bow', [{materials: {'Tungsten Bar': 7}}], STATUS_BOW),
    item('Gold Bow', [{materials: {'Gold Bar': 7}}], STATUS_BOW),
    item('Platinum Bow', [{materials: {'Platinum Bar': 7}}], STATUS_BOW),
    item('Demon Bow', [{materials: {'Demonite Bar': 8}}], STATUS_BOW),
    item('Tendon Bow', [{materials: {'Crimtane Bar': 10}}], STATUS_BOW),
    item('Hellwing Bow', [{materials: {'Cobalt Bar': 7}}], STATUS_BOW),
    item('Iron Bow', [{other: 'Get from the <u>Shadow Chest</u>'}], STATUS_BOW),
    item('The Bee\'s Knees', [{other: '<u>Drop</u> by <u>Queen Bee</u>(33.33%)'}], STATUS_BOW),
    item('Molten Fury', [{materials: {'Hellstone Bar': 15}}], STATUS_BOW),
    item('Marrow', [{other: '<u>Drop</u> by <u>Skeleton Arche</u>(0.5%)'}], STATUS_BOW),
    item('Daedalus Stormbow', [{other: '<u>Drop</u> by <u>Hallowed Mimic</u>(25%)'}], STATUS_BOW),
    item('Ice Bow', [{other: '<u>Drop</u> by <u>Ice Mimic</u>(28.5%)'}], STATUS_BOW),
    item('Shadowflame Bow', [{other: '<u>Drop</u> by <u>Goblin Summoner</u>(16.7%)'}], STATUS_BOW),
    item('Phantasm', [{materials: {'Vortex Fragment': 18}}], STATUS_BOW),
    item('Tsunami', [{other: '<u>Drop</u> by <u>Duke Fishron</u>(20%)'}], STATUS_BOW),
    item('Pulse Bow', [{buy: '<u>Traveling Merchant</u> only after Plantera has been defeated', price: {gold: 45}}], STATUS_BOW),
    item('Cobalt Repeater', [{materials: {'Cobalt Bar': 10}}], STATUS_REPEATER),
    item('Palladium Repeater', [{materials: {'Palladium Bar': 12}}], STATUS_REPEATER),
    item('Mythril Repeater', [{materials: {'Mythril Bar': 10}}], STATUS_REPEATER),
    item('Orichalcum Repeater', [{materials: {'Orichalcum Bar': 12}}], STATUS_REPEATER),
    item('Adamantite Repeater', [{materials: {'Adamantite Bar': 12}}], STATUS_REPEATER),
    item('Titanium Repeater', [{materials: {'Titanium Bar': 13}}], STATUS_REPEATER),
    item('Hallowed Repeater', [{materials: {'Hallowed Bar': 12}}], STATUS_REPEATER),
    item('Chlorophyte Shotbow', [{materials: {'Chlorophyte Bar': 12}}], STATUS_REPEATER),
    item('Stake Launcher', [{other: '<u>Drop</u> by <u>Mounting Wood</u>(14.3%)'}], STATUS_REPEATER),
  // Arrow
    item('Wooden Arrow', [{other: 'Get from the <u>Pot</u> and <u>Chest</u>'}, {materials: {'Wood': 1, 'Stone Block': 1}, pcs: 25}, {buy: '<u>Skeleton Merchant</u>', price: {copper: 5}}], STATUS_ARROW),
    item('Endless Quiver', [{materials: {'Wooden Arrow': 3996}, furnitures: ['Crystal Ball']}], STATUS_ARROW),
    item('Bone Arrow', [{buy: '<u>Skeleton Merchant</u>', price: {copper: 15}}], STATUS_ARROW),
    item('Flaming Arrow', [{other: 'Get from the <u>Pot</u> and <u>Chest</u>'}, {materials: {'Wooden Arrow': 10, 'Torch': 1}, pcs: 10}], STATUS_ARROW),
    item('Frostburn Arrow', [{materials: {'Wooden Arrow': 10, 'Ice Torch': 1}, pcs: 10}], STATUS_ARROW),
    item('Unholy Arrow', [{other: 'Get from the <u>Pot</u> in Hardmode'}, {materials: {'Wooden Arrow': 5, 'Worm Tooth': 1}, pcs: 5}, {buy: '<u>Arms Dealer</u> at night, but after activating Hardmode, become available during the day', price: {copper: 40}}], STATUS_ARROW),
    item('Jester\'s Arrow', [{other: 'Get from the <u>Chest</u>'}, {materials: {'Wooden Arrow': 20, 'Fallen Star': 1}, pcs: 20}], STATUS_ARROW),
    item('Hellfire Arrow', [{other: 'Get from the <u>Pot</u> and <u>Chest</u> in <u>The Underworld</u>'}, {materials: {'Wooden Arrow': 100, 'Hellstone Bar': 1}, pcs: 100}, {buy: '<u>Demolitionist</u> in Hardmode', price: {silver: 1}}], STATUS_ARROW),
    item('Holy Arrow', [{materials: {'Wooden Arrow': 200, 'Pixie Dust': 3, 'Unicorn Horn': 1}, pcs: 200}], STATUS_ARROW),
    item('Cursed Arrow', [{materials: {'Wooden Arrow': 150, 'Cursed Flame': 1}, pcs: 150}], STATUS_ARROW),
    item('Ichor Arrow', [{materials: {'Wooden Arrow': 150, 'Ichor': 1}, pcs: 150}], STATUS_ARROW),
    item('Chlorophyte Arrow', [{materials: {'Chlorophyte Bar': 1}, pcs: 150}], STATUS_ARROW),
    item('Venom Arrow', [{materials: {'Wooden Arrow': 35, 'Vial of Venom': 1}, pcs: 35}], STATUS_ARROW),
    item('Luminite Arrow', [{materials: {'Luminite Bar': 1}, pcs: 333}], STATUS_ARROW),
    item('Stake', [{buy: '<u>Arms Dealer</u> and the <u>Witch Doctor</u> when you have a <u>Stake Launcher</u> in the inventory', price: {copper: 15}}], STATUS_ARROW),
  // Gun
    item('Flintlook Pistol', [{buy: '<u>Arms Dealer</u>', price: {gold: 5}}], STATUS_GUN),
    item('The Undertaker', [{other: 'Get from the <u>Crimson Heart</u>(20%)'}], STATUS_GUN),
    item('Handgun', [{other: 'Get from the <u>Gold Chest</u> in <u>Dungeon</u>'}], STATUS_GUN),
    item('Red Ryder', [{other: 'Get from <u>Presents</u>(0.64%) dropped durning the <u>Chrismas event</u>(7.69%)'}], STATUS_GUN),
    item('Revolver', [{buy: '<u>Traveling Merchant</u> after smashing a <u>Shadow Orb</u> or <u>Crimson Heart</u>', price: {gold: 10}}], STATUS_GUN),
    item('Phoenix Blaster', [{materials: {'Handgun': 1, 'Hellstone Bar': 10}}], STATUS_GUN),
    item('Musket', [{other: 'Get from the <u>Shadow Orb</u>(20%)'}], STATUS_GUN),
    item('Venus Magnum', [{other: '<u>Drop</u> by <u>Plantera</u>(16.67%)'}], STATUS_GUN),
    item('Sniper Rifle', [{other: '<u>Drop</u> by <u>Skeleton Sniper</u>(9%)'}], STATUS_GUN),
    item('Boomstick', [{other: 'Get from the <u>Ivy Chest</u>'}], STATUS_GUN),
    item('Shotgun', [{buy: '<u>Arms Dealer</u> only after the Wall of Flesh has been defeated', price: {gold: 25}}], STATUS_GUN),
    item('Onyx Blaster', [{materials: {'Shotgun': 1, 'Dark Shard': 2, 'Sould of Night': 10}}], STATUS_GUN),
    item('Tactical Shotgun', [{other: '<u>Drop</u> by <u>Tactical Skeleton</u>(9%)'}], STATUS_GUN),
    item('Xenopopper', [{other: '<u>Drop</u> by <u>Martian Saucer</u>(11.1%)'}], STATUS_GUN),
    item('Minishark', [{buy: '<u>Arms Dealer</u>', price: {gold: 35}}], STATUS_GUN),
    item('Clockwork Assault Rifle', [{other: '<u>Drop</u> by <u>Wall of Flesh</u>(16.67%)'}], STATUS_GUN),
    item('Megashark', [{materials: {'Soul of Might': 20, 'Shark Fin': 5, 'Illegal Gun Parts': 1, 'Minishark': 1}}], STATUS_GUN),
    item('Uzi', [{other: '<u>Drop</u> by <u>Angry Trapper</u>(1%)'}], STATUS_GUN),
    item('Chain Gun', [{other: '<u>Drop</u> by <u>Santa-NK1</u>(8.33~12.5%)'}], STATUS_GUN),
    item('Vortex Beater', [{materials: {'Vortex Fragment': 18}}], STATUS_GUN),
    item('S.D.M.G', [{other: '<u>Drop</u> by <u>Moon Lord</u>(11.11%)'}], STATUS_GUN),
    item('Candy Corn Rifle', [{other: '<u>Drop</u> by <u>Pumpking</u>(14.29%)'}], STATUS_GUN),
    item('Coin Gun', [{other: '<u>Drop</u> by <u>Pirate Enemies(excluding the Parrot)</u>(0.0125%) durning the <u>Pirate Invasion</u>'}], STATUS_GUN),
  // Bullet
    item('Musket Ball', [{other: 'Get from the <u>Pot</u>'}, {buy: '<u>Arms Dealer</u>', price: {copper: 7}}], STATUS_BULLET),
    item('Endless Musket Pouch', [{materials: {'Musket Ball': 3996}, furnitures: ['Crystal Ball']}], STATUS_BULLET),
    item('Silver Bullet', [{materials: {'Musket Ball': 70, 'Silver Bar': 1}, pcs: 70}, {buy: '<u>Arms Dealer</u> at the <u>Blood Moon</u>, but after activating Hardmode, become available anytime', price: {copper: 15}}, {other: 'Get from the <u>Pot</u> in Hardmode'}], STATUS_BULLET),
    item('Meteor Shot', [{materials: {'Musket Ball': 70, 'Meteorite Bar': 1}, pcs: 70}], STATUS_BULLET),
    item('Crystal Bullet', [{materials: {'Musket Ball': 100, 'Crystal Shard': 1}, pcs: 100}], STATUS_BULLET),
    item('High Velocity Bullet', [{materials: {'Empty Bullet': 50, 'Cog': 1}, pcs: 50}], STATUS_BULLET),
    item('Party Bullet', [{materials: {'Empty Bullet': 50, 'Confetti': 1}, pcs: 50}], STATUS_BULLET),
    item('Nano Bullet', [{materials: {'Empty Bullet': 50, 'Nanites': 1}, pcs: 50}], STATUS_BULLET),
    item('Exploding Bullet', [{materials: {'Empty Bullet': 50, 'Explosive Powder': 1}, pcs: 50}], STATUS_BULLET),
    item('Golden Bullet', [{materials: {'Empty Bullet': 50, 'Gold Dust': 1}, pcs: 50}], STATUS_BULLET),
    item('Cursed Bullet', [{materials: {'Musket Ball': 150, 'Cursed Flame': 1}, pcs: 150}], STATUS_BULLET),
    item('Ichor Bullet', [{materials: {'Musket Ball': 150, 'Ichor': 1}, pcs: 150}], STATUS_BULLET),
    item('Venom Bullet', [{materials: {'Empty Bullet': 50, 'Vial of Venom': 1}, pcs: 50}], STATUS_BULLET),
    item('Chlorophyte Bullet', [{materials: {'Musket Ball': 70, 'Chlorophyte Bar': 1}, pcs: 70}], STATUS_BULLET),
    item('Luminite Bullet', [{materials: {'Luminite Bar': 1}, pcs: 333}], STATUS_BULLET),
    item('Candy Corn', [{buy: '<u>Arms Dealer</u> when you have a <u>Candy Corn Rifle</u> in the inventory', price: {copper: 5}}], STATUS_BULLET),
  // Launcher
    item('Grenade Launcher', [{other: '<u>Drop</u> by <u>Plantera</u>(16.67%)'}], STATUS_LAUNCHER),
    item('Rocket Launcher', [{other: '<u>Drop</u> by <u>Skeleton Commando</u>(10%)'}], STATUS_LAUNCHER),
    item('Proximity Mine Launcher', [{buy: '<u>Cyborg</u>', price: {gold: 35}}], STATUS_LAUNCHER),
    item('Electrosphere Launcher', [{other: '<u>Drop</u> by <u>Martian Saucer</u>(11.11%)'}], STATUS_LAUNCHER),
    item('Snowman Cannon', [{other: '<u>Drop</u> by <u>Ice Queen</u>(4.4~7.52%)'}], STATUS_LAUNCHER),
    item('Celebration', [{other: '<u>Drop</u> by <u>Moon Lord</u>(11.11%)'}], STATUS_LAUNCHER),
    item('Stynger', [{other: '<u>Drop</u> by <u>Golem</u>(12.5%)'}], STATUS_LAUNCHER),
    item('Jack \'O Lantern Launcher', [{other: '<u>Drop</u> by <u>Pumpking</u>(14.29%)'}], STATUS_LAUNCHER),
    item('Nail Gun', [{other: '<u>Drop</u> by <u>Nailhead</u>(4%)'}], STATUS_LAUNCHER),
  // Rocket
    item('Rocket I', [{buy: '<u>Cyborg</u>', price: {copper: 50}}], STATUS_ROCKET),
    item('Rocket II', [{other: '<u>Buy</u> 2.5 silver from the <u>Cyborg</u> at the <u>Blood Moon</u>'}], STATUS_ROCKET),
    item('Rocket III', [{buy: '<u>Cyborg</u> at night', price: {silver: 1}}], STATUS_ROCKET),
    item('Rocket IV', [{buy: '<u>Cyborg</u> at the Solar Eclipse', price: {silver: 5}}], STATUS_ROCKET),
    item('Stynger Bold', [{buy: '<u>Arms Dealer</u> and the <u>Witch Doctor</u> when you have a <u>Stynger</u> in the inventory', price: {copper: 75}}], STATUS_ROCKET),
    item('Explosive Jack \'O Lantern', [{buy: '<u>Arms Dealer</u> when you have a <u>Jack \'O Lantern Launcher</u> in the inventory', price: {copper: 15}}], STATUS_ROCKET),
    item('Stake', [{buy: '<u>Arms Dealer</u> and the <u>Merchant</u> when you have a <u>Nail Gun</u> in the inventory', price: {silver: 1}}], STATUS_ROCKET),
  // Other Ranged Weapon
    item('Flare Gun', [{other: 'Get from the <u>Gold Chest</u> in <u>Underground</u>'}], STATUS_OTHER_RANGED),
    item('Blowpipe', [{other: 'Get from the <u>Chest</u> in Surface'}], STATUS_OTHER_RANGED),
    item('Blowgun', [{buy: '<u>Witch Doctor</u>', price: {gold: 5}}], STATUS_OTHER_RANGED),
    item('Dart Pistol', [{other: '<u>Drop</u> by <u>Crimson Mimic</u>(20%)'}], STATUS_OTHER_RANGED),
    item('Dart Rifle', [{other: '<u>Drop</u> by <u>Corrupt Mimic</u>(20%)'}], STATUS_OTHER_RANGED),
    item('Snowball Cannon', [{other: 'Get from the <u>Ice Chest</u>'}], STATUS_OTHER_RANGED),
    item('Paintball Gun', [{other: '<u>Drop</u> by <u>Painter</u>(10%)'}], STATUS_OTHER_RANGED),
    item('Harpoon', [{other: '<u>Drop</u> by <u>Goblin Army</u>(0.5%)'}], STATUS_OTHER_RANGED),
    item('Flamethrower', [{materials: {'Iron Bar|Lead Bar': 20, 'Soul of Fright': 20, 'Illegal Gun Parts': 1}}], STATUS_OTHER_RANGED),
    item('Sandgun', [{materials: {'Illegal Gun Parts': 1, 'Topaz': 5, 'Antlion Mandible': 10}}], STATUS_OTHER_RANGED),
    item('Piranha Gun', [{other: 'Get from the <u>Jungle Chest</u> in <u>Dungeon</u>'}], STATUS_OTHER_RANGED),
    item('Elf Melter', [{other: '<u>Drop</u> by <u>Santa-NK1</u>(8.33~12.5%)'}], STATUS_OTHER_RANGED),
    item('Toxikarp', [{other: '<u>Fishing</u> in <u>The Corruption</u> in Hardmode'}], STATUS_OTHER_RANGED),
    item('Star Cannon', [{materials: {'Minishark': 1, 'Meteorite Bar': 20, 'Fallen Star': 5}}], STATUS_OTHER_RANGED),
  // Dart
    item('Seed', [{other: 'Cutting weeds growing on grass when you have a <u>Blowpipe</u> or <u>Blowgun</u> in the inventory'}], STATUS_DART),
    item('Cursed Dart', [{materials: {'Cursed Flame': 1}, pcs: 100}], STATUS_DART),
    item('Ichor Dart', [{materials: {'Ichor': 1}, pcs: 100}], STATUS_DART),
    item('Poison Dart', [{materials: {'Stinger': 1}, pcs: 100}], STATUS_DART),
    item('Crystal Dart', [{materials: {'Crystal Shard': 1}, pcs: 100}], STATUS_DART),
  // Other Ammo
    item('Flare', [{other: 'Get from the <u>Gold Chest</u> that contains a <u>Flare Gun</u>'}, {buy: '<u>Merchant</u> when you have a <u>Flare Gun</u> in the inventory', price: {copper: 7}}], STATUS_OTHER_AMMO),
    item('Blue Flare', [{buy: '<u>Merchant</u> when you have a <u>Flare Gun</u> in the inventory', price: {copper: 7}}], STATUS_OTHER_AMMO),
  // Wand
    item('Wand of Sparking', [{other: 'Get from the <u>Chest</u> in Surface'}], STATUS_WAND),
    item('Amethyst Staff', [{materials: {'Copper Bar': 10, 'Amethyst': 8}}], STATUS_WAND),
    item('Topaz Staff', [{materials: {'Tin Bar': 10, 'Topaz': 8}}], STATUS_WAND),
    item('Sapphire Staff', [{materials: {'Silver Bar': 10, 'Sapphire': 8}}], STATUS_WAND),
    item('Emerald Staff', [{materials: {'Tungsten Bar': 10, 'Emerald': 8}}], STATUS_WAND),
    item('Ruby Staff', [{materials: {'Gold Bar': 10, 'Ruby': 8}}], STATUS_WAND),
    item('Diamond Staff', [{materials: {'Platinum Bar': 10, 'Diamond': 8}}], STATUS_WAND),
    item('Amber Staff', [{materials: {'Sturdy Fossil': 15, 'Amber': 8}}], STATUS_WAND),
    item('Vilethorn', [{other: 'Get from the <u>Shadow Orb</u>(20%)'}], STATUS_WAND),
    item('Crimson Rod', [{other: 'Get from the <u>Crimson Heart</u>(20%)'}], STATUS_WAND),
    item('Magic Missile', [{other: 'Get from the <u>Gold Chest</u> in <u>Dungeon</u>'}], STATUS_WAND),
    item('Flamelash', [{other: 'Get from the <u>Shadow Chest</u>'}], STATUS_WAND),
    item('Ice Rod', [{buy: '<u>Wizard</u>', price: {gold: 50}}], STATUS_WAND),
    item('Crystal Vile Shard', [{other: '<u>Drop</u> by <u>Hallowed Mimic</u>(25%)'}], STATUS_WAND),
    item('Life Drain', [{other: '<u>Drop</u> by <u>Crimson Mimic</u>(20%)'}], STATUS_WAND),
    item('Clinger Staff', [{other: '<u>Drop</u> by <u>Corrupt Mimic</u>(20%)'}], STATUS_WAND),
    item('Frost Staff', [{other: '<u>Drop</u> by <u>Icy Merman</u>, <u>Ice ELemental</u> and <u>Ice Golem</u>(20%)'}], STATUS_WAND),
    item('Meteor Staff', [{materials: {'Meteorite Bar': 20, 'Soul of Light': 10, 'Pixie Dust': 10}}], STATUS_WAND),
    item('Rainbow Rod', [{materials: {'Crystal Shard': 10, 'Unicorn Horn': 2, 'Pixie Dust': 10, 'Soul of Light': 8, 'Soul of Sight': 15}}], STATUS_WAND),
    item('Nimbus Rod', [{other: '<u>Drop</u> by <u>Angry Nimbus</u>(6.67%)'}], STATUS_WAND),
    item('Poison Staff', [{other: '<u>Drop</u> by <u>Black Recluse</u>(2.5%)'}], STATUS_WAND),
    item('Nettle Burst', [{other: '<u>Drop</u> by <u>Plantera</u>(14.29%)'}], STATUS_WAND),
    item('Venom Staff', [{materials: {'Poison Staff': 1, 'Chlorophyte Bar': 14}}], STATUS_WAND),
    item('Staff of Earth', [{other: '<u>Drop</u> by <u>Golem</u>(12.5%)'}], STATUS_WAND),
    item('Shadowbeam Staff', [{other: '<u>Drop</u> by <u>Necromancer</u>(3.33%)'}], STATUS_WAND),
    item('Blizzard Staff', [{other: '<u>Drop</u> by <u>Ice Queen</u>(4.4%)'}], STATUS_WAND),
    item('Inferno Fork', [{other: '<u>Drop</u> by <u>Diabolist</u>(5%)'}], STATUS_WAND),
    item('Spectre Staff', [{other: '<u>Drop</u> by <u>Ragged Caster</u>(5%)'}], STATUS_WAND),
  // Magic Gun
    item('Space Gun', [{materials: {'Meteorite Bar': 20}}], STATUS_MAGIC_GUN),
    item('Bee Gun', [{other: '<u>Drop</u> by <u>Queen Bee</u>(33.3%)'}], STATUS_MAGIC_GUN),
    item('Laser Rifle', [{other: '<u>Drop</u> by <u>Wall of Flesh</u>(16.67%)'}], STATUS_MAGIC_GUN),
    item('Leaf Blower', [{other: '<u>Drop</u> by <u>Plantera</u>(14.29%)'}], STATUS_MAGIC_GUN),
    item('Razorpine', [{other: '<u>Drop</u> by <u>Everscream</u>(5.19%)'}], STATUS_MAGIC_GUN),
    item('Heat Ray', [{other: '<u>Drop</u> by <u>Golem</u>(12.5%)'}], STATUS_MAGIC_GUN),
    item('Bubble Gun', [{other: '<u>Drop</u> by <u>Duke Fishron</u>(20%)'}], STATUS_MAGIC_GUN),
    item('Rainbow Gun', [{other: 'Get from the <u>Hallowed Chest</u> in <u>Dungeon</u>'}], STATUS_MAGIC_GUN),
    item('Wasp Gun', [{other: '<u>Drop</u> by <u>Plantera</u>(16.67%)'}], STATUS_MAGIC_GUN),
    item('Laser Machinegun', [{other: '<u>Drop</u> by <u>Martian Saucer</u>(11.1%)'}], STATUS_MAGIC_GUN),
    item('Charged Blaster Cannon', [{other: '<u>Drop</u> by <u>Martian Saucer</u>(11.11%)'}], STATUS_MAGIC_GUN),
  // Spell Tome
    item('Water Bolt', [{other: 'Get from the many books on the shelves within the <u>Dungeon</u>'}], STATUS_SPELL_TOME),
    item('Book of Skulls', [{other: '<u>Drop</u> by <u>Skeletron</u>(10.5%)'}], STATUS_SPELL_TOME),
    item('Demon Scythe', [{other: '<u>Drop</u> by <u>Demon</u>(2.86%)'}], STATUS_SPELL_TOME),
    item('Golden Shower', [{materials: {'Spell Tome': 1, 'Ichor': 20, 'Soul of Night': 15}, furnitures: ['Bookcase']}], STATUS_SPELL_TOME),
    item('Cursed Flames', [{materials: {'Spell Tome': 1, 'Cursed Flame': 20, 'Soul of Night': 15}, furnitures: ['Bookcase']}], STATUS_SPELL_TOME),
    item('Magnet Sphere', [{other: '<u>Drop</u> by <u>Any Armored Bones</u>(0.25%)'}], STATUS_SPELL_TOME),
    item('Crystal Storm', [{materials: {'Spell Tome': 1, 'Crystal Shard': 20, 'Soul of Light': 15}, furnitures: ['Bookcase']}], STATUS_SPELL_TOME),
    item('Razorblade Typhoon', [{other: '<u>Drop</u> by <u>Duke Fishron</u>(20%)'}], STATUS_SPELL_TOME),
    item('Lunar Flare', [{other: '<u>Drop</u> by <u>Moon Lord</u>(11.11%)'}], STATUS_SPELL_TOME),
  // Other Magic Weapon
    item('Aqua Scepter', [{other: 'Get from the <u>Gold Chest</u> in <u>Dungeon</u>'}], STATUS_OTHER_MAGIC),
    item('Flower of Fire', [{other: 'Get from the <u>Shadow Chest</u>'}], STATUS_OTHER_MAGIC),
    item('Magic Dagger', [{other: '<u>Drop</u> by <u>Mimic</u>(14.29%)'}], STATUS_OTHER_MAGIC),
    item('Magical Harp', [{materials: {'Crystal Shard': 25, 'Soul of Sight': 15, 'Soul of Night': 8, 'Harp': 1}}], STATUS_OTHER_MAGIC),
    item('Medusa Head', [{other: '<u>Drop</u> by <u>Medusa</u>(1%)'}], STATUS_OTHER_MAGIC),
    item('Flower of Frost', [{other: '<u>Drop</u> by <u>Ice Mimic</u>(28.5%)'}], STATUS_OTHER_MAGIC),
    item('Unholy Trident', [{other: '<u>Drop</u> by <u>Red Devil</u>(3.33%)'}], STATUS_OTHER_MAGIC),
    item('Shadowflame Hex Doll', [{other: '<u>Drop</u> by <u>Goblin Summoner</u>(16.7%)'}], STATUS_OTHER_MAGIC),
    item('Sky Fracture', [{materials: {'Magic Missile': 1, 'Light Shard': 2, 'Soul of Light': 10}}], STATUS_OTHER_MAGIC),
    item('Spirit Flame', [{materials: {'Desert Spirit Lamp': 1, 'Forbidden Fragment': 2, 'Soul of Night': 12}}], STATUS_OTHER_MAGIC),
    item('Crystal Serpent', [{other: '<u>Fishing</u> in <u>The Hallow</u>'}], STATUS_OTHER_MAGIC),
    item('Toxic Flask', [{other: '<u>Drop</u> by <u>Dr. Man Fly</u>(2.5%)'}], STATUS_OTHER_MAGIC),
    item('Bat Scepter', [{other: '<u>Drop</u> by <u>Pumpking</u>(14.29%)'}], STATUS_OTHER_MAGIC),
    item('Nebula Arcanum', [{materials: {'Nebula Fragment': 18}}], STATUS_OTHER_MAGIC),
    item('Nebula Blaze', [{materials: {'Nebula Fragment': 18}}], STATUS_OTHER_MAGIC),
    item('Last Prism', [{other: '<u>Drop</u> by <u>Moon Lord</u>(11.11%)'}], STATUS_OTHER_MAGIC),
  // Summon Weapon
    item('Slime Staff', [{other: '<u>Drop</u> by <u>Slime</u> and <u>Slimed Zombie</u>(0.01% <u>Pinky</u>:1% <u>Sand Slime</u>: 0.013%)'}], STATUS_SUMMON),
    item('Hornet Staff', [{materials: {'Bee Wax': 14}}], STATUS_SUMMON),
    item('Imp Staff', [{materials: {'Hellstone Bar': 17}}], STATUS_SUMMON),
    item('Spider Staff', [{materials: {'Spider Fang': 16}}], STATUS_SUMMON),
    item('Optic Staff', [{materials: {'Black Lens': 1, 'Lens': 2, 'Hallowed Bar': 12, 'Soul of Sight': 20}}], STATUS_SUMMON),
    item('Pirate Staff', [{other: '<u>Drop</u> by <u>Pirate Enemies(excluding the Parrot)</u>(0.05%) durning the <u>Pirate Invasion</u>'}], STATUS_SUMMON),
    item('Pygmy Staff', [{other: '<u>Drop</u> by <u>Plantera</u>(25%)'}], STATUS_SUMMON),
    item('Raven Staff', [{other: '<u>Drop</u> by <u>Pumpking</u>(14.29%)'}], STATUS_SUMMON),
    item('Deadly Sphere Staff', [{other: '<u>Drop</u> by <u>Deadly Sphere</u>(2.5%)'}], STATUS_SUMMON),
    item('Tempest Staff', [{other: '<u>Drop</u> by <u>Duke Fishron</u>(20%)'}], STATUS_SUMMON),
    item('Xeno Staff', [{other: '<u>Drop</u> by <u>Martian Saucer</u>(11.1%)'}], STATUS_SUMMON),
    item('Stardust Cell Staff', [{materials: {'Stardust Fragment': 18}}], STATUS_SUMMON),
    item('Stardust Dragon Staff', [{materials: {'Stardust Fragment': 18}}], STATUS_SUMMON),
  // Sentry style Summon Weapon
    item('Qneen Spider Staff', [{materials: {'Spider Fang': 24}}], STATUS_SENTRY_SUMMON),
    item('Staff of the Frost Hydra', [{other: 'Get from the <u>Frozen Chest</u> in <u>Dungeon</u>'}], STATUS_SENTRY_SUMMON),
    item('Lunar Portal Staff', [{other: '<u>Drop</u> by <u>Moon Lord</u>(11.11%)'}], STATUS_SENTRY_SUMMON),
    item('Ranbow Crystal Staff', [{other: '<u>Drop</u> by <u>Moon Lord</u>(11.11%)'}], STATUS_SENTRY_SUMMON),
  // Throwing Weapon
    item('Shuriken', [{other: 'Get from the <u>Pot</u> and <u>Chest</u>'}, {buy: '<u>Merchant</u>', price: {copper: 15}}], STATUS_THROWING),
    item('Throwing Knife', [{other: 'Get from the <u>Chest</u>'}, {buy: '<u>Merchant</u> at the <u>Blood Moon</u>', price: {copper: 15}}], STATUS_THROWING),
    item('Poisoned Knife', [{materials: {'Throwing Knife': 50, 'Vile Powder|Vicious Powder': 1}, pcs: 50}], STATUS_THROWING),
    item('Snowball', [{materials: {'Snow Block': 1}, pcs: 15}], STATUS_THROWING),
    item('Spiky Ball', [{other: '<u>Drop</u> by <u>Goblin Army</u>(20%)'}, {buy: '<u>Goblin Tinkerer</u>', price: {copper: 80}}], STATUS_THROWING),
    item('Bone', [{other: '<u>Drop</u> by <u>Angry Bones</u>, <u>Dark Caster</u> and <u>Cursed Skull</u>(98.07%)'}], STATUS_THROWING),
    item('Bone Glove', [{other: 'Get from the <u>Treasure Bag(Skeletron)</u>'}], STATUS_THROWING),
    item('Rotten Egg', [{other: 'Get from the <u>Goodie Bag</u>(32.89%) dropped durning the <u>Halloween event</u>(1.25%)'}], STATUS_HOOK),
    item('Star Anise', [{other: 'Get from <u>Presents</u>(6.34%) dropped durning the <u>Chrismas event</u>(7.69%)'}], STATUS_GUN),
    item('Molotov Cooktail', [{materials: {'Ale': 5, 'Pink Gel': 1, 'Silk': 1, 'Torch': 1}, pcs: 5}], STATUS_THROWING),
    item('Frost Daggerfish', [{other: '<u>Fishing</u> in the <u>Snow</u>'}], STATUS_THROWING),
    item('Javelin', [{other: '<u>Drop</u> by <u>Hoplite</u>(50%)'}], STATUS_THROWING),
    item('Bone Throwing Knife', [{materials: {'Sturdy Fossil': 1}, pcs: 25}], STATUS_THROWING),
    item('Holy Water', [{materials: {'Bottled Water': 10, 'Pixie Dust': 2, 'Hallowed Seeds': 1}, pcs: 10}], STATUS_THROWING),
    item('Unholy Water', [{materials: {'Bottled Water': 10, 'Ebonsand Block': 2, 'Corrupt Seeds': 1}, pcs: 10}], STATUS_THROWING),
    item('Blood Water', [{materials: {'Bottled Water': 10, 'Crimsand Block': 2, 'Crimson Seeds': 1}, pcs: 10}], STATUS_THROWING),
  // Explosive Weapon
    item('Grenade', [{other: 'Get from the <u>Chest</u>'}, {buy: '<u>Demolitionist</u>', price: {copper: 75}}], STATUS_EXPLOSIVE),
    item('Sticky Grenade', [{materials: {'Grenade': 5, 'Gel': 1}, pcs: 5}], STATUS_EXPLOSIVE),
    item('Bouncy Grenade', [{materials: {'Grenade': 2, 'Pink Gel': 1}, pcs: 2}], STATUS_EXPLOSIVE),
    item('Bomb', [{other: 'Get from the <u>Pot</u> and <u>Chest</u>'}, {buy: '<u>Demolitionist</u>', price: {silver: 3}}, {other: 'Get from the <u>Bomb Statue</u>'}], STATUS_EXPLOSIVE),
    item('Sticky Bomb', [{materials: {'Bomb': 1, 'Gel': 1}}], STATUS_EXPLOSIVE),
    item('Bouncy Bomb', [{materials: {'Bomb': 1, 'Pink Gel': 1}}], STATUS_EXPLOSIVE),
    item('Dynamite', [{other: 'Get from the <u>Chest</u>'}, {buy: '<u>Demolitionist</u>', price: {silver: 20}}], STATUS_EXPLOSIVE),
    item('Sticky Dynamite', [{materials: {'Dynamite': 1, 'Gel': 1}}], STATUS_EXPLOSIVE),
    item('Bouncy Dynamite', [{materials: {'Dynamite': 1, 'Pink Gel': 1}}], STATUS_EXPLOSIVE),
    item('Beenade', [{other: '<u>Drop</u> by <u>Qneen Bee</u>(75%)'}, {materials: {'Grenade': 1, 'Bee Wax': 1}}], STATUS_EXPLOSIVE),
    item('Bomb Fish', [{other: '<u>Fishing</u>'}], STATUS_EXPLOSIVE),
    item('Explosives', [{other: 'Get from the <u>Underground</u>'}, {materials: {'Dynamite': 3, 'Wire': 1}}], STATUS_EXPLOSIVE),
    item('Happy Grenade', [{other: '<u>Drop</u> by <u>Party Girl</u>(25%) initially killed'}, {buy: '<u>Party Girl</u> if in the inventory', price: {silver: 2, copper: 50}}], STATUS_EXPLOSIVE),
  // Placeable Weapon
    item('Snowball Launcher', [{other: '<u>Drop</u> by <u>Snow Flinx</u>(0.67%)'}], STATUS_PLACEABLE_WEAPON),
    item('Cannon', [{buy: '<u>Pirate</u>', price: {gold: 25}}], STATUS_PLACEABLE_WEAPON),
    item('Bunny Cannon', [{buy: '<u>Pirate</u>', price: {gold: 50}}], STATUS_PLACEABLE_WEAPON),
    item('Land Mine', [{buy: '<u>Demolitionist</u> only after the Plantera and Pirate Invasion has been defeated', price: {gold: 5}}], STATUS_PLACEABLE_WEAPON),
    
    /*
    item('Ice', [{other: 'Get from the <u>Ice Chest</u>'}]),
    item('Bee', [{other: '<u>Drop</u> by <u>Crimson Mimic</u>(20%)'}]),
    item('Cobalt', [{materials: {'Cobalt Bar': 10}}]),
    item('Purple', [{other: '<u>Fishing</u> in <u>The Corruption</u>'}]),
    item('Mushroom', [{buy: '<u>Truffle</u>', price: {gold: 70}}]),
    item('Red Ryder', [{other: 'Get from <u>Presents</u>(0.64%) dropped durning the <u>Chrismas event</u>(7.69%)'}], STATUS_GUN),
    */
  ];
})();
console.timeEnd('load-items');